# Generated by Django 6.0.7 on 2026-08-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_receptionist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_date', 'appointment_time')},
        ),
    ]
